language: node_js
node_js:
- '8.9.4'
before_install: npm install -g gulp-cli
deploy:
  provider: s3
  access_key_id:
    secure: HbVROoper2avv4xh/xVsnJF8MO/4vWWRSjDyLqtEra+o8xtlUdxjuBQkfSqQtOKBsaXvNfxhUCAJVKPk2tLHwyyZA12bnBeQvqlK7PysYkgNFDBik/s5i2EpDL79E7cfcrUP4w4KEIUEaa1l+KIbV/miJBdsA+L1dY759rwnEVs=
  secret_access_key:
    secure: Ew77WWHPy5h0kcgg9nM0mGWMIh5uiej0qlRtlgfm2Mfr5cdGonhTytJitDRqRJbDLArxCBpw3fe6Sazr72WnhVCqbJOrfYpvlIXk+RSK1leOKEsY7/jIdAYAaRwCh9mhQ79kvgJBkgDRA3UyzYgvCVFxhqRaHdXEF60SU+r8oeY=
  bucket: static.bombbomb.com
  skip_cleanup: true
  acl: public_read
  local_dir: build
  upload-dir: js